# Generated by Django 2.2.3 on 2019-07-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgSyncCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('code', models.CharField(blank=True, max_length=150, null=True)),
                ('nonce', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('id_token', models.CharField(blank=True, max_length=1500, null=True)),
                ('access_token', models.CharField(blank=True, max_length=1500, null=True)),
                ('expires_in', models.IntegerField(default=0)),
                ('refresh_token', models.CharField(blank=True, max_length=150, null=True)),
                ('token_type', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QDProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('EPAID', models.CharField(blank=True, max_length=50, null=True)),
                ('Rate', models.IntegerField(default=0)),
                ('RateUnits', models.IntegerField(default=0)),
                ('LoadOrder', models.IntegerField(default=0)),
                ('Total', models.IntegerField(default=0)),
                ('TotalizerUnits', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'qdProducts',
            },
        ),
        migrations.CreateModel(
            name='QDWorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WOID', models.CharField(blank=True, max_length=50, null=True)),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('Client', models.CharField(blank=True, max_length=50, null=True)),
                ('Farm', models.CharField(blank=True, max_length=50, null=True)),
                ('Field', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('County', models.CharField(blank=True, max_length=50, null=True)),
                ('Legal', models.CharField(blank=True, max_length=50, null=True)),
                ('Crop', models.CharField(blank=True, max_length=50, null=True)),
                ('Pest', models.CharField(blank=True, max_length=50, null=True)),
                ('TotalCarrierRate', models.IntegerField(default=0)),
                ('Acres', models.IntegerField(default=0)),
                ('CarrierUnits', models.IntegerField(default=0)),
                ('TotalCarrier', models.IntegerField(default=0)),
                ('EffectiveApplicationRate', models.IntegerField(default=0)),
                ('PreLoad', models.IntegerField(default=0)),
                ('ProdRinseDelay', models.IntegerField(default=0)),
                ('PostRinseDelay', models.IntegerField(default=0)),
                ('Carrier2Preload', models.IntegerField(default=0)),
                ('Completed', models.IntegerField(default=0)),
                ('Sent2Website', models.IntegerField(default=0)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'qdWorkOrders',
                'ordering': ['WOID'],
            },
        ),
        migrations.CreateModel(
            name='QDProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('EPAID', models.CharField(blank=True, max_length=50, null=True)),
                ('Rate', models.IntegerField(default=0)),
                ('RateUnits', models.IntegerField(default=0)),
                ('LoadOrder', models.IntegerField(default=0)),
                ('Total', models.IntegerField(default=0)),
                ('TotalizerUnits', models.IntegerField(default=0)),
                ('WorkOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prods', to='mainPage.QDWorkOrder')),
            ],
            options={
                'verbose_name_plural': 'qdProds',
            },
        ),
        migrations.CreateModel(
            name='QDCarrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('EPAID', models.CharField(blank=True, max_length=50, null=True)),
                ('Rate', models.IntegerField(default=0)),
                ('LoadOrder', models.IntegerField(default=0)),
                ('WorkOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carriers', to='mainPage.QDWorkOrder')),
            ],
            options={
                'verbose_name_plural': 'qdCarriers',
            },
        ),
    ]
