# Generated by Django 2.2.3 on 2019-07-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QDProduct',
        ),
    ]
