# Generated by Django 2.2.3 on 2019-07-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_delete_qdproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qdcarrier',
            name='WorkOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Carriers', to='mainPage.QDWorkOrder'),
        ),
        migrations.AlterField(
            model_name='qdprod',
            name='WorkOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Prods', to='mainPage.QDWorkOrder'),
        ),
    ]
