# Generated by Django 2.2.3 on 2019-07-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_auto_20190716_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='qdworkorder',
            name='ControllerUpToDate',
            field=models.IntegerField(default=0),
        ),
    ]
