# Generated by Django 2.2.3 on 2019-07-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_qdworkorder_controlleruptodate'),
    ]

    operations = [
        migrations.AddField(
            model_name='agsynccredential',
            name='assetId',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
